In [19]:
from getCleanData23 import get_clean_data
import pandas as pd

pd.set_option('display.max_columns', None)

cleanData = get_clean_data("AAPL", "2021-08-03", "2021-08-04")
cleanData.head(20)

Trade Query for AAPL 2021-08-03 2021-08-04

INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport.sftp:[chan 1] Opened sftp connection (server version 3)

Saved trades for AAPL on 2021-08-03 00:00:00

Quote Query for AAPL 2021-08-03 2021-08-04

INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport.sftp:[chan 1] Opened sftp connection (server version 3)

Saved Quotes for AAPL on 2021-08-03 00:00:00

KeyError: 'Bid_Price'

In [22]:
import getData
import preprocessData
import pandas as pd

from sklearn.pipeline import make_pipeline

tradesDf = pd.read_csv("/home/jake/TAQ-Query-Scripts/data/raw_data/2021-08-03/AAPL_trades.csv")
quotesDf = pd.read_csv("/home/jake/TAQ-Query-Scripts/data/raw_data/2021-08-03/AAPL_quotes.csv") 
# get data
allData = pd.concat([tradesDf, quotesDf], axis=0)

# intialize preprocessing pipeline
process_pipeline = make_pipeline(preprocessData.PreprocessData())

# clean data
df_clean = process_pipeline.fit_transform(allData)

df_clean.head(20)

KeyError: 'Bid_Price'

In [28]:
pd.set_option('display.max_columns', None)
quotesDf.head(10)

,Unnamed: 0.1,Unnamed: 0,Time,Date,Exchange,Symbol,Trade_Volume,Trade_Price,Sale_Condition,Source_of_Trade,Trade_Stop_Stock_Indicator,Trade_Correction_Indicator,Sequence_Number,Trade_Id,Trade_Reporting_Facility,Participant_Timestamp,Trade_Reporting_Facility_TRF_Timestamp,Trade_Through_Exempt_Indicator
0,0,0,2021-08-03 04:00:00.085215,2021-08-03,P,AAPL,921,146.1,@ T,N,NaN,0,1690,1,,40000084847104,NaN,1
1,1,1,2021-08-03 04:00:00.311956,2021-08-03,K,AAPL,200,146.1,@ T,N,NaN,0,1718,1,,40000311741000,NaN,0
2,2,2,2021-08-03 04:00:00.311963,2021-08-03,K,AAPL,60,146.1,@ TI,N,NaN,0,1719,2,,40000311741000,NaN,0
3,3,3,2021-08-03 04:00:00.311969,2021-08-03,K,AAPL,5,146.1,@ TI,N,NaN,0,1720,3,,40000311741000,NaN,0
4,4,4,2021-08-03 04:00:00.311972,2021-08-03,K,AAPL,6,146.1,@ TI,N,NaN,0,1721,4,,40000311741000,NaN,0
5,5,5,2021-08-03 04:00:00.311978,2021-08-03,K,AAPL,2,146.1,@ TI,N,NaN,0,1722,5,,40000311741000,NaN,0
6,6,6,2021-08-03 04:00:00.311983,2021-08-03,K,AAPL,5,146.1,@ TI,N,NaN,0,1723,6,,40000311741000,NaN,0
7,7,7,2021-08-03 04:00:00.311997,2021-08-03,K,AAPL,88,146.1,@ TI,N,NaN,0,1724,7,,40000311741000,NaN,0
8,8,8,2021-08-03 04:00:01.860893,2021-08-03,P,AAPL,2,146.1,@ TI,N,NaN,0,1771,2,,40001860528128,NaN,0
9,9,9,2021-08-03 04:00:03.150579,2021-08-03,P,AAPL,4,146.1,@FTI,N,NaN,0,1794,3,,40003150214144,NaN,1

In [29]:
tradesDf.head(10)

,Unnamed: 0.1,Unnamed: 0,Time,Date,Exchange,Symbol,Trade_Volume,Trade_Price,Sale_Condition,Source_of_Trade,Trade_Stop_Stock_Indicator,Trade_Correction_Indicator,Sequence_Number,Trade_Id,Trade_Reporting_Facility,Participant_Timestamp,Trade_Reporting_Facility_TRF_Timestamp,Trade_Through_Exempt_Indicator
0,0,0,2021-08-03 04:00:00.085215,2021-08-03,P,AAPL,921,146.1,@ T,N,NaN,0,1690,1,,40000084847104,NaN,1
1,1,1,2021-08-03 04:00:00.311956,2021-08-03,K,AAPL,200,146.1,@ T,N,NaN,0,1718,1,,40000311741000,NaN,0
2,2,2,2021-08-03 04:00:00.311963,2021-08-03,K,AAPL,60,146.1,@ TI,N,NaN,0,1719,2,,40000311741000,NaN,0
3,3,3,2021-08-03 04:00:00.311969,2021-08-03,K,AAPL,5,146.1,@ TI,N,NaN,0,1720,3,,40000311741000,NaN,0
4,4,4,2021-08-03 04:00:00.311972,2021-08-03,K,AAPL,6,146.1,@ TI,N,NaN,0,1721,4,,40000311741000,NaN,0
5,5,5,2021-08-03 04:00:00.311978,2021-08-03,K,AAPL,2,146.1,@ TI,N,NaN,0,1722,5,,40000311741000,NaN,0
6,6,6,2021-08-03 04:00:00.311983,2021-08-03,K,AAPL,5,146.1,@ TI,N,NaN,0,1723,6,,40000311741000,NaN,0
7,7,7,2021-08-03 04:00:00.311997,2021-08-03,K,AAPL,88,146.1,@ TI,N,NaN,0,1724,7,,40000311741000,NaN,0
8,8,8,2021-08-03 04:00:01.860893,2021-08-03,P,AAPL,2,146.1,@ TI,N,NaN,0,1771,2,,40001860528128,NaN,0
9,9,9,2021-08-03 04:00:03.150579,2021-08-03,P,AAPL,4,146.1,@FTI,N,NaN,0,1794,3,,40003150214144,NaN,1

In [ ]:
import generateFeatures as gf
featureData = gf.generate_features(cleanData)
featureData.head(20)